name: Run DoveScraper

on:
  schedule:
    # Run every 7 days at 00:00 UTC
    - cron: '0 0 */7 * *'

  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify your required Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests  # Add any other dependencies your script requires

    - name: Run DoveScraper.py
      run: |
        python DoveScraper.py
